### ISSUE TITLE
TODO Subset Training

### ISSUE THREAD

**Issue by ridmajayasundara** [cepdnaclk/e18-4yp-GPU-Acceleration-for-Deep-Learning-based-Comprehensive-ECG-analysis#43]
### Classification
- [ ] Train on Subset A (save the model)
- [ ] Train on Subset B (save the model)

### Regression
Train and save models for all 4 parameters :

#### From Subset A
- [x] HR
- [x] QRS
- [x] PR
- [x] QT

#### From Subset B
- [x] HR
- [x] QRS
- [x] PR
- [x] QT

### Transfer Classification
- [ ] Transfer Classification from A to B

### Transfer Regression
Transfer Regression from A to B for the following:
- [x] HR
- [x] QRS
- [x] PR
- [x] QT

### Transfer Classification to Regression
Transfer Classification from A to **Regression B(for each parameter)**
- [ ] HR
- [ ] QRS
- [ ] PR
- [ ] QT

### Transfer Regression to Classification
Transfer **Regression from A (from each parameter)** to Classification B 
- [ ] HR
- [ ] QRS
- [ ] PR
- [ ] QT
